import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("add", "routes/add.tsx"),
  route("add/scan", "routes/add-scan.tsx"),
  route("collection", "routes/collection.tsx"),
  route("wishlist", "routes/wishlist.tsx"),
  route("sets", "routes/sets.tsx"),
  route("sets/:setId", "routes/set-detail.tsx"),
  route("pokemon", "routes/pokemon.tsx"),
  route("binders", "routes/binders.tsx"),
  route("binders/:binderId", "routes/binder-detail.tsx"),
  route("grading", "routes/grading.tsx"),
  route("trade", "routes/trade.tsx"),
  route("sealed", "routes/sealed.tsx"),
  route("sealed/add", "routes/sealed-add.tsx"),
  route("sealed/:productId", "routes/sealed-product.tsx"),
  route("import", "routes/import.tsx"),
  route("s/b/:token", "routes/share-binder.tsx"),
  route("s/c/:token", "routes/share-collection.tsx"),
  route("settings", "routes/settings.tsx"),
  route("whats-new", "routes/whats-new.tsx"),
  route("export/:format", "routes/export.tsx"),
  route("api/auth/*", "routes/api.auth.tsx"),
  route("api/card-thumb", "routes/api.card-thumb.tsx"),
] satisfies RouteConfig;
